---
releases:
- name: "turbulence"
  version: "0.11.0-dev.1"
  url: "https://storage.googleapis.com/kubo-pipeline-store/turbulence/turbulence-release-v0.11.0-dev.1"
  sha1: "6a3a1c20010396cb78c1ada39b0a68053f14a016"

addons:
- name: turbulence_agent
  jobs:
  - name: turbulence_agent
    release: turbulence
    consumes:
      api:
        instances:
        - address: ((internal_ip))
        properties:
          advertised_host: ""
          username: turbulence
          password: ((turbulence_api_password))
          agent_listen_port: 8081
          cert:
            ca: ((turbulence_api_ca.ca))
  exclude:
    stemcell:
    - os: windows2019
