platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
inputs:
- name: git-kubo-ci
- name: gcs-kubeconfig
run:
  path: ./git-kubo-ci/tasks/run-istio-tests/task.sh
