platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfkubo/kubo-ci
    tag: stable
run:
  path: git-kubo-ci/scripts/upload-release.sh

params:
  RELEASE_PATH: release/*.tgz

inputs:
  - name: git-kubo-ci
  - name: kubo-lock
  - name: release
